# Needed because open_port's typespec is incorrect
# in earlier versions, see
# https://github.com/erlang/otp/commit/b9051f0f94c3d9f56f9d8d9b9c316446db7fd7a9
# and there are no upstream Elixir docker images with OTP 23
image: erlang:23-alpine

variables:
  MIX_ENV: test
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - deps
    - _build

stages:
  - test
  - publish

before_script:
  - apk add elixir build-base cmake
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix compile --force

lint:
  stage: test
  script:
    - mix format --check-formatted

unit-testing:
  stage: test
  coverage: '/(\d+\.\d+\%) \| Total/'
  script:
    - mix test --trace --preload-modules --cover

dialyzer:
  stage: test
  script:
  - mix dialyzer
